package br.com.univesp.clinicaesteticaapi.domain.enums;

public enum ProcedureType {
    LIMPEZA_PELE,
    BOTOX,
    LASER_CLAREAMENTO,
    JATO_PLASMA,
    PEELING,
    MICROAGULHAMENTO,
    REVITALIZAÇÃO_FACIAL,
    DEPILACAO_LASER,
    MASSAGEM_RELAXANTE,
    DRENAGEM_LINFATICA,
    VENTOSSATERAPIA,
    ACUPUNTURA,
    TAPPING,
    LASERTERAPIA,
    OZONIOTERAPIA,
    TRATAMENTO_GORDURA,
    TRATAMENTO_CELULITE,
    POS_OPERATORIO
}
